//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseMaintanenceForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedTo
    {
        public int ID { get; set; }
        public string JobNumber { get; set; }
        public string AssignedToID { get; set; }
        public string JobFolderURL { get; set; }
        public string AssignedToPhoneExt { get; set; }
    
        public virtual AssignedToNameData AssignedToNameData { get; set; }
    }
}
